In [1]:
import numpy as np
import pandas as pd 

# Creating numpy array in different ways

In [5]:
data = np.full(2,3)
data

array([3, 3])

In [11]:
datam = np.zeros(5)
datam

array([0., 0., 0., 0., 0.])

In [13]:
x = np.random.rand(2,3)
x

array([[0.43646901, 0.18508207, 0.48516407],
       [0.78364944, 0.58828428, 0.56595157]])

In [17]:
y = np.linspace(0,1, 10)
y

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Numpy array indexing


In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr[0]

array([1, 2, 3])

In [21]:
arr[0,1]

2

In [25]:
arr[1,1]

5

In [26]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


In [30]:
#stacking arrays
import numpy as np

# input array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking 2 1-d arrays
c = np.stack((a, b),axis=1)
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [34]:
x=np.array([[1,2,3],
            [4,5,6]])
y=np.array([[7,8,9],
            [10,11,12]])
z=np.array([[13,14,15],
            [16,17,18]])

np.stack((x,y,z),axis=1)

array([[[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18]]])